##nombre de la aplicacion
spring.application.name=discografia  
##cadena de coneccion  
spring.mongodb.uri=mongodb+srv://brianbrowncoopman_db_user:Q1s0RjWjlmwUWd9r@discografica-db.dxinrpm.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=discografica-db
## nombre de la bbdd
spring.mongodb.database=discografica-db



## todo esto deberia estar en variables de entorno .env


